version: '3.8'

networks:
    nodeapp-network:
      driver: bridge

services:
  node:
    container_name: nj-no-gain
    build: .
    command: ["./wait-for-it.sh", "--timeout=25", "mysql:3306", "--", "node", "build/index.js"]
    ports:
      - 8000:8000
    networks:
      - nodeapp-network
    depends_on:
      - mysql

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3307:3306
    networks:
      - nodeapp-network
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: njnogain
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: '%'

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nodeapp-network
    volumes:
      - /var/www/:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/

